name: Java CI
on:
  push:
    branches:
    - 'sonarqube'
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}   
    - name: Build with Gradle
      run: ./gradlew check testReport testSuiteReport sonarqube --no-daemon --parallel --continue -Dsonar.login=${{ secrets.SONAR_LOGIN }}
    - name: Upload Jacoco Report
      uses: actions/upload-artifact@v1
      with:
        name: jacoco-report
        path: build/reports/jacoco/codeCoverageReport
    - name: Upload Test Report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/all-tests
    - name: Upload Test Suite Report
      uses: actions/upload-artifact@v1
      with:
        name: test-suite-report
        path: build/reports/test-suite
